from __future__ import annotations

from collections.abc import Callable
from typing import Any

from xknx.cemi import CEMIFrame, CEMIMessageCode

from knx_gui.plugins.virtual.virtual_device import VirtualDevice
from knx_gui.plugins.virtual.virtual_router import VirtualRouter, VirtualRouterState


class VirtualService:
    """Owns the virtual router and virtual device lifecycle."""

    def __init__(self) -> None:
        self._logger: Any = None
        self._cemi_listener: Callable[[bytes], None] | None = None
        self._router = VirtualRouter()
        self.device = VirtualDevice()

    def set_logger(self, logger: Any) -> None:
        self._logger = logger
        self.device.set_logger(logger)

    def set_cemi_listener(self, listener: Callable[[bytes], None] | None) -> None:
        self._cemi_listener = listener

    @property
    def router_state(self) -> VirtualRouterState:
        return self._router.state

    @property
    def router_error(self) -> str | None:
        return self._router.error

    @property
    def gateway_connected(self) -> bool:
        return self._router.gateway_connected

    def start_router(self, name: str, port: int, multicast_group: str) -> None:
        self._router = VirtualRouter(
            name=name,
            port=port,
            multicast_group=multicast_group,
            on_cemi=self._handle_routing_cemi,
            on_gateway_cemi=self._handle_gateway_cemi,
            logger=self._logger,
        )
        self._router.start()

    def stop_router(self) -> None:
        self._router.stop()

    def _handle_routing_cemi(self, raw: bytes) -> None:
        """CEMI received over multicast routing - replies go back the same way."""
        if self._cemi_listener is not None:
            self._cemi_listener(raw)
        for reply in self.device.handle_cemi(raw):
            self._router.send_cemi(reply)

    def _handle_gateway_cemi(self, raw: bytes) -> None:
        """CEMI received over the point-to-point TCP gateway - replies stay on that
        same private channel rather than going out over routing, where they'd never
        reach a client that's specifically connected via tunnelling instead."""
        if self._cemi_listener is not None:
            self._cemi_listener(raw)
        self._confirm_if_request(raw)
        for reply in self.device.handle_cemi(raw):
            self._router.send_gateway_cemi(reply.to_knx())

    def _confirm_if_request(self, raw: bytes) -> None:
        """A tunnelling client blocks waiting for an L_Data.con confirming every
        L_Data.req it sends - normally generated by whatever bridges the tunnel
        to the actual bus. Over routing, xknx's own client synthesizes that
        confirmation locally the moment it puts a frame on the multicast socket
        (see xknx.io.routing.Routing.send_cemi), so nothing is needed here for
        the routing path - but the gateway *is* the client's only bridge to
        this virtual bus, so we have to send it back ourselves."""
        try:
            cemi = CEMIFrame.from_knx(raw)
        except Exception:
            return
        if cemi.code is not CEMIMessageCode.L_DATA_REQ:
            return
        cemi.code = CEMIMessageCode.L_DATA_CON
        self._router.send_gateway_cemi(cemi.to_knx())

    def shutdown(self) -> None:
        self._router.stop()
